version: '3'

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - server
      - client

  server:
    build:
      context: ./zio-chat-server
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 8081

  client:
    build:
      context: ./zio-chat-client
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 80
