version: '3'

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped

  server:
    build:
      context: ./zio-chat-server
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 8081
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped

  client:
    build:
      context: ./zio-chat-client
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 80
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped

networks:
  letsencrypt-docker-compose:
    name: letsencrypt-docker-compose_default
    external: true
