global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['server:8081']

remote_write:
  - url: '<remote write url>'
    basic_auth:
      username: '<remote write username>'
      password: '<remote write api key>'
