version: '3'

volumes:
  prometheus_data: {}

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped

  server:
    build:
      context: ../bytebrain-server
      dockerfile: Dockerfile
    volumes:
      - ./db/app:/app/db
    depends_on:
      - weaviate
    env_file: .env
    expose:
      - 8081
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped

  client:
    build:
      context: ../bytebrain-client
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - 80
    networks:
      - letsencrypt-docker-compose
    restart: unless-stopped

  weaviate:
    image: semitechnologies/weaviate:1.21.5
    expose:
      - 8080
    restart: on-failure:0
    volumes:
      - ./db/weaviate:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'generative-openai'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - letsencrypt-docker-compose

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ../bytebrain-server/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - letsencrypt-docker-compose

networks:
  letsencrypt-docker-compose:
    name: letsencrypt-docker-compose_default
    external: true
