[tool.poetry]
name = "zio-chat"
version = "0.1.0"
description = "Chat with ZIO"
authors = ["Milad Khajavi"]

[tool.poetry.dependencies]
python = "3.10.11"
fastapi = "^0.95.1"
langchain = "0.0.177"
openai = "0.27.4"
tiktoken = "0.3.3"
chromadb = "0.3.21"
unstructured = "0.5.13"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
webserver = "zio_chat.restapi:start"
index = "zio_chat.index:index"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
